AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://matt-go-dev/08f59081f8ab21fc1bfcda6efdbfcb91
      Handler: hello
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
Outputs:
  HelloAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello/
  HelloFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloFunction
      - Arn
  HelloFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloFunctionRole
      - Arn
